tunnel:f5a69335-4167-4df3-a27f-b1a5b142aa2f
credentials-file:f5a69335-4167-4df3-a27f-b1a5b142aa2f.json

ingress:
  - hostname: app.jiawei800705.tk
    service: http://jia800.herokuapp.com
  - service: http_status:404
